manifest:
  defaults:
    revision: main

  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos/
    - name: arribada
      url-base: https://github.com/arribada/

  projects:
    - name: zephyr
      remote: zephyr
      path: zephyr
      revision: v3.5.0
      import:
        name-allowlist:
          - cmsis # required by the ARM port
          - hal_rpi_pico
          - hal_stm32 
          - hal_espressif
    - name: arribada-custom-boards
      path: deps/custom-boards
      revision: v3.5.0
      url: https://github.com/arribada/custom-boards-zephyr

  self:
    path: m6e-nano-driver-zephyr
